# Generated by Django 5.1.2 on 2024-12-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_doctor_password_patient_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='password',
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
